version: '3.0'
  
services:
  partyb:
    image: corda/corda-zulu-java1.8-4.5
    container_name: partyb
    ports:
      - "10008:10008"
      - "10009:10009"
      - "2222:2222"
    volumes:
      - ./partyb/node.conf:/etc/corda/node.conf
      - ./partyb/certificates:/opt/corda/certificates
      - ./partyb/persistence:/opt/corda/persistence
      - ./partyb/logs:/opt/corda/logs
      - ./shared/cordapps:/opt/corda/cordapps
      - ./shared/additional-node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters


  partyc:
    image: corda/corda-zulu-java1.8-4.5
    container_name: partyc
    ports:
      - "10011:10011"
      - "10012:10012"
      - "3333:3333"
    volumes:
      - ./partyc/node.conf:/etc/corda/node.conf
      - ./partyc/certificates:/opt/corda/certificates
      - ./partyc/persistence:/opt/corda/persistence
      - ./partyc/logs:/opt/corda/logs
      - ./shared/cordapps:/opt/corda/cordapps
      - ./shared/additional-node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters